### ISSUE TITLE
Source problem

### ISSUE THREAD

**Issue by shenlinyong** [rpmccordlab/Radial-CT-Analysis-HiC#1]
This python script you've written is fantastic! But the species I'm analyzing is chicken. So I need to change some parts of the python script, but I don't know what `chrNL`,`chrNLpos`, `chrNF`, `chrNM` means?

```bash
chrNL = np.array([19,22,17,16,1,15,12,21,14,6,20,9,10,2,5,11,3,8,18,7,23,13,4]) # Boyle
chrNLpos = np.array([0.229,0.249,0.275,0.290,0.299,0.330,0.330,0.339,0.339,0.339,0.349,0.349,0.349,0.349,0.360,0.360,0.371,0.371,0.371,0.371,0.371,0.371,0.389]) # Boyle
chrNF = np.array([22,21,18,17,20,14,16,15,19,11,12,13,6,10,9,8,7,1,23,3,2,4,5])
chrNFpos = np.array([0.53,0.55,0.57,0.58,0.61,0.62,0.62,0.63,0.63,0.65,0.65,0.66,0.68,0.68,0.72,0.73,0.74,0.75,0.75,0.76,0.77,0.77,0.79])
chrNM = np.array([21,16,18,15,12,11,4,1]) # Firtz
chrNMpos = np.array([0.482,0.549,0.564,0.593,0.614,0.659,0.682,0.736]) # Firtz
```

**Comment by priyojitDas** [comment]
> This python script you've written is fantastic! But the species I'm analyzing is chicken. So I need to change some parts of the python script, but I don't know what `chrNL`,`chrNLpos`, `chrNF`, `chrNM` means?
> 
> ```shell
> chrNL = np.array([19,22,17,16,1,15,12,21,14,6,20,9,10,2,5,11,3,8,18,7,23,13,4]) # Boyle
> chrNLpos = np.array([0.229,0.249,0.275,0.290,0.299,0.330,0.330,0.339,0.339,0.339,0.349,0.349,0.349,0.349,0.360,0.360,0.371,0.371,0.371,0.371,0.371,0.371,0.389]) # Boyle
> chrNF = np.array([22,21,18,17,20,14,16,15,19,11,12,13,6,10,9,8,7,1,23,3,2,4,5])
> chrNFpos = np.array([0.53,0.55,0.57,0.58,0.61,0.62,0.62,0.63,0.63,0.65,0.65,0.66,0.68,0.68,0.72,0.73,0.74,0.75,0.75,0.76,0.77,0.77,0.79])
> chrNM = np.array([21,16,18,15,12,11,4,1]) # Firtz
> chrNMpos = np.array([0.482,0.549,0.564,0.593,0.614,0.659,0.682,0.736]) # Firtz
> ```

Hi @shenlinyong,

Those are some previously published microscopy imaging data used for validation purposes. chrNL represents the order of the chromosomes in lymphoblastoid nuclei (from center to periphery) found using microscopy and chrNLpos holds their positions reported. Similarly, chrNF, and chrNM represent fibroblast and epithelial nuclei respectively. If you ever use human Hi-C data from any of these types of cells, then those values can be used to validate the inferred results. Or these can be used to see how different the ordering is for your cell of interest from the canonical cell types.

For now, as you are working on the chicken data, you may ignore these variables and comment out the last couple of lines of the codes where the predicted results are compared with the imaging results. Otherwise, if you have chicken chromosome radial position imaging data already, you can use them there.

Thank you- PD

**Comment by shenlinyong** [comment]
Hi,  @priyojitDas 
I had some trouble, I got 6 samples of the Dist.txt file bynet2dist.py.  I modified the code in dist2rad.py because there were 0 values.
```bash
data = np.loadtxt(dfilename)
np.nan_to_num(data, nan=0.00001,copy=False)
data=data+0.00001
```
This gives me results for 3 samples, but the other three *Dist.txt files still have problems.
```bash
/home/SLY68/anaconda3/envs/hicpro/lib/python3.7/site-packages/numpy/lib/function_base.py:2691: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/home/SLY68/anaconda3/envs/hicpro/lib/python3.7/site-packages/numpy/lib/function_base.py:2692: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]
Traceback (most recent call last):
  File "/home/SLY68/biosoft/Radial-CT-Analysis-HiC/dist2rad.py", line 208, in <module>
    gd_order = cp_tune(data_gd)
  File "/home/SLY68/biosoft/Radial-CT-Analysis-HiC/dist2rad.py", line 125, in cp_tune
    pc = pca.fit_transform(dataCorr)
  File "/home/SLY68/anaconda3/envs/hicpro/lib/python3.7/site-packages/sklearn/decomposition/_pca.py", line 407, in fit_transform
    U, S, Vt = self._fit(X)
  File "/home/SLY68/anaconda3/envs/hicpro/lib/python3.7/site-packages/sklearn/decomposition/_pca.py", line 431, in _fit
    X, dtype=[np.float64, np.float32], ensure_2d=True, copy=self.copy
  File "/home/SLY68/anaconda3/envs/hicpro/lib/python3.7/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/home/SLY68/anaconda3/envs/hicpro/lib/python3.7/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/home/SLY68/anaconda3/envs/hicpro/lib/python3.7/site-packages/sklearn/utils/validation.py", line 116, in _assert_all_finite
    type_err, msg_dtype if msg_dtype is not None else X.dtype
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```
Attached are the *Dist.txt files that I had problems with
[leanDist.txt](https://github.com/rpmccordlab/Radial-CT-Analysis-HiC/files/10088356/leanDist.txt)
